### ISSUE TITLE
appLayout.querySelector is not a function

### ISSUE THREAD

**Issue by Camatobe** [TheLastProject/lovelace-media-art-background#10]
URL/community_plugin/lovelace-media-art-background/media-art-background.js:30:30 Uncaught TypeError: appLayout.querySelector is not a function

URL/community_plugin/lovelace-media-art-background/media-art-background.js:65:12 Uncaught TypeError: Cannot read property 'style' of null

This 2 Errors are irregularly showing up in my log and my js dev console in the frontend.

I think they are related. querySelector seems not to work anymore?
It was working with 0.103 I guess. 

I am using Core 0.105.2
Installed your plugin via hacs

My Config: 
```
media_art_background:
  blur: 10px
  entities:
    - media_player.spotify
    - entity: media_player.spotify
      image_attribute: entity_picture
      valid_states:
        - playing
  opacity: 0.5
  transition_opacity: 2s
```

If you need more Information let me know.
