### ISSUE TITLE
Uncaught TypeError: Cannot read property 'transition_opacity' of undefined

### ISSUE THREAD

**Issue by OliPassey** [TheLastProject/lovelace-media-art-background#13]
media-art-background.js:4 Uncaught TypeError: Cannot read property 'transition_opacity' of undefined
    at setupStyle (media-art-background.js:4)
    at media-art-background.js:83

I've tried to pull through the currently playing fan art from kodi - got things loaded but no matter what, i get this error.
Any ideas? I've tried commenting parts out, trying different values, quotes, dropping the s on 2s etc

```
    media_art_background:
      blur: 10px
      opacity: 0.5
      transition_opacity: 2s
      entities:
        - entity: media_player.kodi_studio_tv
          valid_states:
            - playing
          image_attribute: entity_picture
```

**Comment by TheLastProject** [comment]
The actual error here is that `lovelace.config.media_art_background` is undefined. Where did you put the configuration? It needs to be in Edit Dashboard -> Raw configuration editor.

(I'm seeing now I really did not document that clearly, oops)

**Comment by OliPassey** [comment]
Thank you! I have the config posted above in the the raw config editor, but installed via HACS so have not put the resource URL in the raw config editor.
I'll try switching it.

**Comment by TheLastProject** [comment]
The resources thing is no longer relevant either, Home Assistant changed that a few releases ago but Home Assistant should set that correctly.

Do you have it at the start of the raw config editor? So not inside a view or anything?

Example:
```
media_art_background:
  entities:
    - media_player.living_room_tv
title: Home
views:
  - title: Today
    path: today
    icon: 'mdi:clock'
    badges:
      - entity: sensor.time
```
