### ISSUE TITLE
019-11-09 00:27:33 ERROR (MainThread) [frontend.js.latest.201910251] http://nosuch:8123/community_plugin/lovelace-media-art-background/media-art-background.js:4:64 Uncaught TypeError: Cannot read property 'transition_opacity' of undefined

### ISSUE THREAD

**Issue by geezuh** [TheLastProject/lovelace-media-art-background#8]
I installed from HAC and added the recommended into the raw config editor:

```
resources:
  - type: module
    url: /community_plugin/mini-media-player/mini-media-player-bundle.js
  - type: module
    url: /community_plugin/lovelace-media-art-background/media-art-background.js
title: Home
media_art_background:
  blur: 10px
  entities:
    - media_player.main
    - entity: media_player.snapcast
      image_attribute: entity_picture
      valid_states:
        - playing
  opacity: 0.5
```
